print("Hello World!")
print("Hello Again!")
print("Hello\tWorld\t!")
print("Hi\tWorld\t!")
print("Hey\tAll\t!")
print("Yo\tEarth\t!")
print("Hello\nWorld\n!")
print("Hi\nWorld\n!")
print("Hey\nAll\n!")
print("Yo\nEarth\n!")
print("The \\t character is my favorite special character!")
print(r"The \t character is my favorite special character!")
print("The \\","t character is my favorite special character!",sep='')
a = input(input)

print('a'+ a)
